# 1. Ligação à Base de Dados (TUDO NA MESMA LINHA)
spring.datasource.url=jdbc:h2:file:./dados_psicoagenda;AUTO_SERVER=TRUE;
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Configurações de Hibernação e Dialeto
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Consola Web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true